// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://autmfgexgynllabhggig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dG1mZ2V4Z3lubGxhYmhnZ2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDcyMjcsImV4cCI6MjA3Mjg4MzIyN30.ZshJAcaiMtmIfh-CQ7ytfX_u37PSqd3Esrlq1Dvgb4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});